title: KANILA
description: "Ruang kontemplasi Banyu Kanila. Lakukan semua dengan hati, maka akan sampai juga pada hati."
baseurl: ""
url: "https://kanila.web.id"

# Pengaturan Markdown
markdown: kramdown
highlighter: rouge

# File yang diabaikan
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/

# Pengaturan Koleksi Tulisan
collections:
  puisi:
    output: true
    permalink: /puisi/:title/
  opini:
    output: true
    permalink: /opini/:title/
