backend:
  name: github
  repo: banyungr-cmyk/Kanila-project
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "opini"
    label: "Celoteh"
    folder: "_opini"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Judul", name: "title", widget: "string"}
      - {label: "Tanggal", name: "date", widget: "datetime", format: "YYYY-MM-DD"}
      - {label: "Isi Tulisan", name: "body", widget: "markdown"}

  - name: "puisi"
    label: "Antologi Aksara"
    folder: "_puisi"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Judul", name: "title", widget: "string"}
      - {label: "Tanggal", name: "date", widget: "datetime", format: "YYYY-MM-DD"}
      - {label: "Isi Puisi", name: "body", widget: "markdown"}
